apiVersion: notification-ctrlr.netop-types.io/v1alpha1
kind: Notification
metadata:
  creationTimestamp: null
  name: aci-containers-system-acc-provision-config-configmap-core-v1
spec:
  clusterName: bm2acicni
  objRef:
    apiVersion: v1
    kind: ConfigMap
    name: acc-provision-config
    namespace: aci-containers-system
  serializedObj: '{"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"acc-provision-config","namespace":"aci-containers-system","creationTimestamp":null},"data":{"spec":"{\n    \"acc_provision_input\":
    {\n        \"operator_managed_config\": {\n            \"enable_updates\": false\n        },\n        \"aci_config\":
    {\n            \"system_id\": \"bm2acicni\",\n            \"apic_hosts\": [\n                \"10.30.120.140\"\n            ],\n            \"aep\":
    \"bm-srvrs-aep\",\n            \"vrf\": {\n                \"name\": \"sauto_l3out-1_vrf\",\n                \"tenant\":
    \"common\"\n            },\n            \"l3out\": {\n                \"name\":
    \"sauto_l3out-1\",\n                \"external_networks\": [\n                    \"sauto_l3out-1_epg\"\n                ]\n            }\n        },\n        \"registry\":
    {\n            \"image_prefix\": \"quay.io/noirolabs\", \n            \"image_pull_secret\":
    \"noiro-docker-registry-secret\"\n        },\n        \"kube_config\": {\n            \"drop_log_config\":
    {}, \n            \"image_pull_policy\": \"Always\", \n            \"istio_config\":
    {}, \n            \"multus\": {}, \n            \"nodepodif_config\": {}, \n            \"operator_managed_config\":
    {}, \n            \"ovs_memory_limit\": \"0.75Gi\", \n            \"sriov_config\":
    {}\n\n        },\n        \"logging\": {\n           \"controller_log_level\":
    \"debug\", \n           \"hostagent_log_level\": \"debug\", \n           \"opflexagent_log_level\":
    \"debug\"\n        },\n        \"net_config\": {\n            \"infra_vlan\":
    4093,\n            \"service_vlan\": 102, \n            \"kubeapi_vlan\": 101,\n            \"extern_static\":
    \"10.4.0.1/16\",\n            \"extern_dynamic\": \"10.3.0.2/16\",\n            \"node_svc_subnet\":
    \"10.5.0.1/16\",\n            \"node_subnet\": \"1.100.101.1/24\",\n            \"pod_subnet\":
    \"10.6.0.1/16\"\n        }\n    }\n }"}}'
status:
  state: ""
