apiVersion: notification-ctrlr.netop-types.io/v1alpha1
kind: Notification
metadata:
  creationTimestamp: null
  name: alokk8s23-aci-containers-system-acc-provision-config-configmap-core-v1
spec:
  clusterName: alokk8s23
  objRef:
    apiVersion: v1
    kind: ConfigMap
    name: acc-provision-config
    namespace: aci-containers-system
  serializedObj: '{"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"acc-provision-config","namespace":"aci-containers-system","creationTimestamp":null},"data":{"spec":"{\n    \"acc_provision_input\":
    {\n        \"operator_managed_config\": {\n            \"enable_updates\": false\n        },\n        \"aci_config\":
    {\n            \"system_id\": \"alok_k8s23\",\n            \"apic_hosts\": [\n                \"10.30.120.180\"\n            ],\n            \"aep\":
    \"hypf-aep\",\n            \"vrf\": {\n                \"name\": \"k8s23_vrf\",\n                \"tenant\":
    \"common\"\n            },\n            \"l3out\": {\n                \"name\":
    \"k8s23\",\n                \"external_networks\": [\n                    \"k8s23_net\"\n                ]\n            }\n        },\n        \"registry\":
    {\n            \"image_prefix\": \"quay.io/noirolabs\", \n            \"image_pull_secret\":
    \"noiro-docker-registry-secret\", \n            \"aci_containers_controller_version\":
    \"kmr2-test\", \n            \"aci_containers_host_version\": \"kmr2-test\", \n            \"cnideploy_version\":
    \"kmr2-test\", \n            \"opflex_agent_version\": \"kmr2-test\", \n            \"openvswitch_version\":
    \"kmr2-test\", \n            \"snat_operator_version\": \"kmr2-test\"\n        },\n        \"kube_config\":
    {\n            \"image_pull_policy\": \"Always\", \n            \"ovs_memory_limit\":
    \"1Gi\"\n\n        },\n        \"logging\": {\n           \"controller_log_level\":
    \"debug\", \n           \"hostagent_log_level\": \"debug\", \n           \"opflexagent_log_level\":
    \"debug\"\n        },\n        \"net_config\": {\n            \"infra_vlan\":
    3901,\n            \"service_vlan\": 46, \n            \"kubeapi_vlan\": 45,\n            \"extern_static\":
    \"10.4.0.1/24\",\n            \"extern_dynamic\": \"10.3.0.1/24\",\n            \"node_svc_subnet\":
    \"10.5.0.1/24\",\n            \"node_subnet\": \"192.168.23.1/24\",\n            \"pod_subnet\":
    \"10.2.0.1/16\"\n        }\n    }\n }"}}'
status:
  state: ""
